name: Validate New Issues
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check required fields
        uses: actions/github-script@v6
        with:
          script: |
            // 修复点1: 从 payload 获取仓库信息
            const repoOwner = context.repo.owner || context.payload.repository.owner.login;
            const repoName = context.repo.repo || context.payload.repository.name;
            const issueNumber = context.issue.number || context.payload.issue.number;
            
            console.log(`验证仓库: ${repoOwner}/${repoName}, Issue: #${issueNumber}`);
            
            // 修复点2: 确保标签存在
            try {
              await github.rest.issues.getLabel({
                owner: repoOwner,
                repo: repoName,
                name: "needs-info"
              });
              console.log("needs-info 标签已存在");
            } catch (error) {
              console.log("创建 needs-info 标签");
              await github.rest.issues.createLabel({
                owner: repoOwner,
                repo: repoName,
                name: "needs-info",
                color: "FFD700",
                description: "需要补充信息"
              });
            }

            // 验证必填字段
            const issueBody = context.payload.issue.body || "";
            console.log("Issue 内容:", issueBody.substring(0, 100) + "..."); // 打印部分内容
            
            // 修复点3: 使用更灵活的检测方法
            const requiredKeys = ["环境版本", "复现步骤"];
            const isInvalid = requiredKeys.some(key => 
              !issueBody.toLowerCase().includes(key.toLowerCase())
            );
            
            console.log("Issue 是否有效:", !isInvalid);
            
            if (isInvalid) {
              console.log("添加 needs-info 标签和评论");
              
              // 添加标签
              await github.rest.issues.addLabels({
                issue_number: issueNumber,
                owner: repoOwner,
                repo: repoName,
                labels: ["needs-info"]
              });
              
              // 添加评论
              await github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: repoOwner,
                repo: repoName,
                body: "⚠️ 请补充以下必填信息：\n- 环境版本\n- 复现步骤"
              });
            }